name: lerndex
description: "Lernsoftware für Kinder"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0

  # Google Login
  google_sign_in: ^6.2.1

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # Firebase Vertex AI
  firebase_vertexai: 1.8.3

  # Für Foto-Upload
  image_picker: 1.0.7
  firebase_storage: ^12.0.0

  # Konfetti-Effekt
  confetti: ^0.7.0

  fl_chart: ^0.69.0

  # Code-Generatoren
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # KI-Tutor
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.6.18
  http: ^1.2.0
  firebase_ai: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

  # Code-Generatoren
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/lerndex_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#7B1FA2"
  adaptive_icon_foreground: "assets/images/lerndex_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/questions/
    - assets/images/